### ISSUE TITLE
working with python3

### ISSUE THREAD

**Issue by raviapatel** [SudoDEM/SudoDEM#1]
I am trying to install sudoDEM however I see in installation instruction sudodem  depends heavily on python2 is python3 version with latest qt coming soon...
regards
Ravi

**Comment by SwaySZ** [comment]
Hi Ravi,
Yes, it is on our to-do list to upgrade Python 2 to Python 3. However, there is no such an urgency 'cause Python 3 would not bring additional benefits.
Sway

**Comment by SudoDEM** [comment]
Upgraded to Python 3 and Qt5.
