### ISSUE TITLE
outputVTK write no polydata

### ISSUE THREAD

**Issue by alundilong** [SudoDEM/SudoDEM#11]
Hi Developer,

I wanted to express my appreciation for the exceptional work on sudoDEM. It's truly remarkable and opens up numerous possibilities where traditional spherical particle models fall short.

### Reproduction Steps:
1. Following Section 4.1 of the QuickGuide, I integrated the necessary code for data output.
   ![image](https://github.com/SudoDEM/SudoDEM/assets/24465615/5d1c8e71-53c6-4f63-b7c0-5af4d74a1593)
2. Next, I crafted a new script as outlined below,
3. Executed `sudodem3d newscript.py`, resulting in the successful creation of a VTK file, albeit with 0 polydata (the loaded xml.bz2 file contains complete data).
   ![image](https://github.com/SudoDEM/SudoDEM/assets/24465615/5c2009ab-32a2-4a01-9967-7a02f65bc822)
4. I ensured that I was using the released code version.

Thank you for your attention to this matter!

**Comment by SwaySZ** [comment]
Hi,

Please double-check if the saved file "*.xml.bz2" contains the information of superquadric particles. The function outputVTK  only works for superquadric particles.

Sway

**Comment by alundilong** [comment]
thanks!
