### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by maarten157** [SudoDEM/SudoDEM#12]
Hello,

I would like to install SudoDEM and use it with python 3 but I'm getting some errors which I believe are linked to the python and package versions. What is the python version you work with and what are the package versions which are used (pip list)? 

Thanks in advance,
Maarten

**Comment by SwaySZ** [comment]
Hi Maarten,

Not sure how you install it. You may follow the quick instructions for installation. 

Best,
Sway

**Comment by maarten157** [comment]
Hi Sway, 

Thanks for the suggestion but the quick instructions seems not to be updated for the python 3 release. A requirements.txt file would be very helpful. 

Kind regards,
Maarten

**Comment by SwaySZ** [comment]
> Hi Sway,
> 
> Thanks for the suggestion but the quick instructions seems not to be updated for the python 3 release. A requirements.txt file would be very helpful.
> 
> Kind regards, Maarten

Sorry for the messy instructions. You may follow this one at scripts/HowToUseScripts.md.

Sway
