### ISSUE TITLE
Regarding SudoDEM installation on Windows Subsystem Linux (WSL)

### ISSUE THREAD

**Issue by saidenesnuray** [SudoDEM/SudoDEM#13]
Dear all,

I am a user of YADE. I have conducted a comprehensive calibration and validitation study on KFS with YADE. However, especially undrained loading condition calibration results are not promising as much as drained ones. I am expecting these inaccurate calibration on undrained conditions is because of the simplified particle shape of spheres since undrained behavior is strongly depends on volume changes.

Therefore, I am planning to run my simulations on SudoDEM since it enables to use advanced particle shapes in the scope of my master's thesis. However, I am not a user of Linux and I am running my YADE simulations on WSL which I want to run SudoDEM simulations as well. Yet, even though I spent a couple of hours on the installation process I could not manage to set it up on my WSL. I followed the instructions either in the user manual and on GitHub page. Therefore, I contacted to Mr. Shiwei ZHAO and he kindly directed me to open an issue on GitHub page since he knows some fellows who set it up on WSL. Beside, he suggested to install Xming to use GUI. So, I need your helps regarding the installation process of SudoDEM on WSL.

Thanks for your kind helps in advance.

Best,
Enes

**Comment by SwaySZ** [comment]
Hi Enes,

There is nothing special about installing or compiling a code in WSL from a Linux machine. If you failed to install or compile SudoDEM, please show the errors here that might be helpful.

Sway

**Comment by saidenesnuray** [comment]
Hi Sway,

Thanks for your kind help in advance.

I am an Ubuntu 20.04 user and already compiled files are avaliable on GitHub for that version. Therefore, I preferred to install SudoDEM from the compiled files as follows





# HOW TO USE THE SCRIPTS FOR QUICK INSTALLATION and COMPILATION
## Using compiled executables
You can download the compiled executables from the [release page](https://github.com/SudoDEM/3rdlibs/releases/latest) on GitHub. Or type
the following commands in a terminal to download them.
```bash
wget https://github.com/SudoDEM/3rdlibs/releases/tag/v1.7.3/SudoDEM2D-ubuntu-20.04.tar.xz
wget https://github.com/SudoDEM/3rdlibs/releases/tag/v1.7.3/SudoDEM3D-ubuntu-20.04.tar.xz
```
## Using compiled 3rdlibs
We have compiled the 3rd-party libraries on Ubuntu 20.04 so that you can reuse them.
1. Install some tools for compilation, e.g., gcc, cmake, etc. You will be asked for the root permission.
```bash
./install3rd_base.sh
```
2. Download the compiled 3rd-party libraries
```bash
./install3rdcore_ubuntu20.04.sh
```
3. Compile SudoDEM2D
```bash
./firstCompile_SudoDEM2D.sh
```
4. Compile SudoDEM3D
```bash
./firstCompile_SudoDEM3D.sh







I followed the four steps above. I run all the codes in the folder “scripts”.
First I made sure my Ubuntu version is 20.04 then I installed cmake and gcc. Then I run “./install3rd_base.sh”.  and “./install3rdcore_ubuntu20.04.sh” which I did not have any problem with. 


However, after I run “./firstCompile_SudoDEM2D.sh” and “./firstCompile_SudoDEM3D.sh” I am getting the following error for either in 2D or 3D.






[ 27%] Built target _GLViewer
[ 28%] Linking CXX shared library libsudodem.so
/usr/bin/ld: /usr/local/lib/libbz2.a(bzlib.o): relocation R_X86_64_PC32 against symbol `BZ2_crc32Table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sudodem.dir/build.make:745: libsudodem.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/sudodem.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[  1%] Automatic MOC for target _GLViewer
[  1%] Built target _GLViewer_autogen
[  9%] Built target _GLViewer
[ 24%] Built target qhull
[ 25%] Linking CXX shared library libsudodem.so
/usr/bin/ld: /usr/local/lib/libbz2.a(bzlib.o): relocation R_X86_64_PC32 against symbol `BZ2_crc32Table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sudodem.dir/build.make:745: libsudodem.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/sudodem.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
./firstCompile_SudoDEM2D.sh: line 13: cd: too many arguments
cp: cannot stat '3rdlib/3rdlibs': No such file or directory



Additionally, can you please tell me exactly where I should use "Xming" and how to connect SudoDEM and Xming ? 

Also, would you recommend me to install SudoDEM from source code or am I on the right way by trying to install it via compiled files ? 


Best,
Enes

**Comment by SwaySZ** [comment]
Hi Enes,

Just download the compiled files at the latest release page if you prefer not to compile everything from scratch. You are now trying to compile the source code. The error shows an issue related with the library libbz2 (the latest compiled 3rdlibs has compiled libbz2 from its source not from sudo apt install). 

Sway

**Comment by saidenesnuray** [comment]
Hi Sway,

I solved the problem with your guidance. 

Many thanks,
Enes
