### ISSUE TITLE
Unstable computation 

### ISSUE THREAD

**Issue by WeijianLiang** [SudoDEM/SudoDEM#2]
In bool SuperellipseLaw::go(shared_ptr<IGeom>& ig, shared_ptr<IPhys>& ip, Interaction* I) function, some interaction may be removed and could potentially leads to unstable computation, commenting out the following could solve this problem in a dirty way. 

  // // erase the interaction when aAbB shows separation, otherwise keep it to be
  // // able to store previous separating plane for fast detection of separation
  // if (A->bound->min[0] >= ab_max[0] || ab_min[0] >= A->bound->max[0] ||
  //     A->bound->min[1] >= ab_max[1] || ab_min[1] >= A->bound->max[1]) {
  //   phys->normalForce = Vector2r(0., 0.);
  //   phys->shearForce = Vector2r(0., 0.);
  //   scene->interactions->requestErase(I);
  //   if ((id1 == 19 && id2 == 399) || (id1 == 399 && id2 == 19)) {
  //     std::cout << "watch dog 1" << !I->geom << "\n";
  //   }
  //   return false;
  // }
However, the source of the bug still need be found out.

**Comment by SwaySZ** [comment]
fixed in v1.3.7
